### ISSUE TITLE
Deal with Abelian/Commutative objects better.

### ISSUE THREAD

**Issue by johnynek** [twitter/algebird#128]
There are often optimizations the can be done if a semigroup/monoid/group is commutative.

How can we best communicate that?

Two obvious solutions: a property of the instance (`.isCommutative`). This rules out the ability to have some methods that only apply to commutative objects (because that check is at runtime).

A second type-class approach would be something like:

``` scala
// use this to check at runtime:
sealed trait CommutativeStatus[O] {
  def commutes: Boolean
}
trait IsNotCommutative[O] extends CommutativeStatus[O] { val commutes = false }
// use this when you want to require commutativity
trait IsCommutative[O] extends CommutativeStatus[O] { val commutes = true }

trait LowP {
  implicit def defaultIsNot[O]: CommutativeStatus new IsNotCommutative[O] { }
}

object CommutativeStatus extends LowP {
  implicit def commutes[O](implicit isc: IsCommutative[O]): CommutativeStatus = isc
}
```

We can add instances of IsCommutative to the Monoid/Group/Semigroup objects.

**Comment by sritchie** [comment]
@johnynek , I propose that we close this since we're adopting shared typeclasses soon.
