### ISSUE TITLE
Mergeable summaries

### ISSUE THREAD

**Issue by avibryant** [twitter/algebird#177]
There's some good stuff in here that's very relevant:
http://www.cse.ust.hk/~huangzf/mergeable.pdf

In particular, it describes how to merge SpaceSaver, which is the best-performing heavy-hitters estimator.

**Comment by mannykao** [comment]
Hi, I found this looking for code for mergeable summaries. Looks like this project is much more than that.  Does it contain an implementation of it that I can use as a starting point?

Thanks.

**Comment by jnievelt** [comment]
We have several mergeable summaries implemented, which are kept in the core project:

https://github.com/twitter/algebird/tree/develop/algebird-core/src/main/scala/com/twitter/algebird

I'm not sure what this issue was originally intended to track, but it seems we should be able to close it?
