### ISSUE TITLE
StatefulSummer should return TraversableOnce[V] not Option[V]

### ISSUE THREAD

**Issue by johnynek** [twitter/algebird#214]
We can easily imagine cases where we want to flush more than one item.

This is currently done with Option[Traversable[V]] which is a bit of a hack and limits the composability.

Consider changing this to a

``` scala
// These compose well
trait BufferedOperator[M[_],U,V] {
  def monad: Monad[M]
  def put(u: U): M[V]
  def flush: M[V]
  def isFlushed: Boolean
}

trait StatefulSummer[V] extends BufferedOperator[Option,V,V] {
  def monad = OptionMonad
  def semigroup: Semigroup[V]
}

```

**Comment by sritchie** [comment]
Can we close this, @johnynek? Looks like we already made some other enhancements.
