### ISSUE TITLE
Moving Average is mentioned on front page, but unable to find in code

### ISSUE THREAD

**Issue by phaefele** [twitter/algebird#233]
On the main wiki page it mentions that Algebird handles moving average calculations, but I am unable to find which class implements this. I'd like to understand the code for this in more detail. I searched the codebase and the docs, but wasn't able to find anything that looked likely. If someone could point me to the right file, that would be very helpful. Thanks in advance.

**Comment by sritchie** [comment]
We're finally implementing this data structure, with a monoid! Track progress here:

https://github.com/twitter/algebird/issues/558
