### ISSUE TITLE
Possible off by 1 error for QTrees

### ISSUE THREAD

**Issue by joshualande** [twitter/algebird#377]
+ @avibryant 

I was playing around with the QTree, and I think there may be an off-by one error in the implementation.

Consider this code snippet:
```scala
import com.twitter.algebird.{QTree,QTreeSemigroup}

val K = 10
implicit val qtreeSemigroup = new QTreeSemigroup[Double](K)

val l = (1 to 3).map { _.toDouble }
val qt = l.map { v =>QTree(v)}.reduceLeft( qtreeSemigroup.plus)
qt.quantileBounds(0.5)
```
This returns: 
```
res39: (Double, Double) = (1.0,1.0000152587890625)
```
Shouldn't the median of the list (1, 2, 3) be 2, not 1?

Out of curiosity, I tried the numbers 1 to 11, and got a median of 5 instead of 6.

And I tried the numbers 1 to 101 and got a median of 50 instead of 51.

I also tried a K of 100,000 but still get a median of 50 (for 1 to 101)

I think this is caused by an off-by-one error in the QTree implementation.

I don't think an off-by-one bug would cause any practical problems since I have lots of data, but it might be worth investigating.

Thanks!

Joshua

**Comment by johnynek** [comment]
I see two tasks here: 1) convert Josh's examples into property tests. 2) fix the issue.

**Comment by joshualande** [comment]
Awesome, thanks so much!
