### ISSUE TITLE
This repo should be deleted

### ISSUE THREAD

**Issue by MasseGuillaume** [twitter/algebird#415]
[this evidence](https://github.com/twitter/algebird/blob/0.9.0/algebird-core/src/main/scala/com/twitter/algebird/Monad.scala#L39) is a blatant disregard to [Twitter's effective scala guidelines](http://twitter.github.io/effectivescala/#Types and Generics)

**Comment by johnynek** [comment]
I assume this is a joke and a critique of that guide. Also, the joke seems to rely on the idea that somehow all of the engineers at Twitter have one opinion which is accurately reflected in the guide.

**Comment by travisbrown** [comment]
@MasseGuillaume Effective Scala only explicitly mentions type-level programming, and it's possible to draw a reasonably clear line between e.g. type-level arithmetic and the use of abstractions like monads.

I personally think that some of the language in Effective Scala (notably "these techniques rarely find useful application in production code") is a little more confrontational than is necessary, and may not be as accurate now as it was when the guide was written. I suspect that a PR that toned down the fightiness (without changing the prohibition) would be better received than this issue.

**Comment by MasseGuillaume** [comment]
@johnynek yep just trolling. I was kinda chocked when I found the citation @travisbrown mentionned.
