### ISSUE TITLE
Remove Extension on MonoidAggregator at next release.

### ISSUE THREAD

**Issue by johnynek** [twitter/algebird#416]

**Comment by ianoc** [comment]
little more context might be good, not sure what you mean here?

**Comment by johnynek** [comment]
:) I am adding a pull request, but I want to add this issue now. :)

**Comment by ianoc** [comment]
Ahh ok, makes more sense! :)

**Comment by johnynek** [comment]
Fracking compiler bug won't let me enrich MonoidAggregator. Giving up.
