### ISSUE TITLE
QTree pruneChildrenWhere is really slow

### ISSUE THREAD

**Issue by johnynek** [twitter/algebird#429]
We are seeing jobs using more than 60% of their CPU in that method. This is uncommon on hadoop (usually the most expensive stuff is serialization, sorting and compression).

**Comment by avibryant** [comment]
Yeah, I was worried about that. I think pruning on every merge is probably crazy; it's just not clear to me what the best heuristic is to decide when it's worth pruning.

**Comment by sritchie** [comment]
@johnynek can we close now that #433 is merged?
