### ISSUE TITLE
How do I get started with this project ?

### ISSUE THREAD

**Issue by bismoy2013** [twitter/algebird#432]
Is there any way that I can contribute to this project ? Hope someone can get back to me on this .

**Comment by isnotinvain** [comment]
Pull requests are always welcome! Just "fork" the repository and send a pull request.
You can take a look at the open issues as well, or start a discussion on https://groups.google.com/forum/#!forum/algebird

**Comment by bismoy2013** [comment]
Sure :) that definitely makes sense !

**Comment by johnynek** [comment]
@bismoy2013 also look at the open issues. We have a ton. You can ask for clarification as needed. We are trying to get better about using labels as well.
