### ISSUE TITLE
add sumOption to GeneratedProductMacros

### ISSUE THREAD

**Issue by johnynek** [twitter/algebird#446]
See: https://github.com/twitter/algebird/blob/develop/algebird-core/src/main/scala/com/twitter/algebird/GeneratedProductAlgebra.scala

Issues:

1) sumOption is not implemented.
2) Monoid does not extend the Semigroup (and on down), so it also does not have a fast sum.

Need to follow more closely the approach of Tuple:
https://github.com/twitter/algebird/blob/develop/algebird-core/src/main/scala/com/twitter/algebird/GeneratedAbstractAlgebra.scala

Requirements: make it binary compatible.

**Comment by sid-kap** [comment]
I took care of (2) in PR #457

**Comment by sritchie** [comment]
Closed by #588
