### ISSUE TITLE
Can't import QTree in the Spark shell

### ISSUE THREAD

**Issue by erinshellman** [twitter/algebird#451]
Hey, I'm getting weird behavior where I'm able to import some classes from algebird into the Spark shell, but not others (specifically QTree). Seen this before?

```{scala}
spark-shell --jars ~/jars/algebird-core_2.10-0.1.11.jar
Spark assembly has been built with Hive, including Datanucleus jars on classpath
15/06/18 10:35:21 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 1.3.0
      /_/

Using Scala version 2.10.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_45)
Type in expressions to have them evaluated.
Type :help for more information.
Spark context available as sc.
SQL context available as sqlContext.

scala> import com.twitter.algebird._
import com.twitter.algebird._

scala> import com.twitter.algebird.QTree
<console>:22: error: object QTree is not a member of package com.twitter.algebird
       import com.twitter.algebird.QTree
              ^
```

**Comment by ianoc** [comment]
version 0.1.11 is ancient, did QTree even exist in that artifact? 
https://github.com/twitter/algebird/releases/tag/0.1.11

its from 2013

**Comment by erinshellman** [comment]
Ah, sorry, went with the jar that's in the maven repository. That's probably it.

**Comment by ianoc** [comment]
Should all be in maven central, http://search.maven.org/#artifactdetails%7Ccom.twitter%7Calgebird-core_2.10%7C0.10.2%7Cjar  looks to be the latest 2.10 artifact there.

**Comment by bigsnarfdude** [comment]
It works fine for me. There are issues with Spark REPL but it is on the Spark side...https://issues.apache.org/jira/browse/SPARK-7944

**Comment by erinshellman** [comment]
Yeah it works with the latest jar on maven central. Was getting the latest from http://mvnrepository.com/ which is out of date. My baaaaad, thanks!

**Comment by ianoc** [comment]
Ok good, will close this
