### ISSUE TITLE
SparseCMS

### ISSUE THREAD

**Issue by johnynek** [twitter/algebird#461]
Might be good to have a SparseCMS that keeps a map of values until the size of the map reaches `depth * width`. This could improve accuracy for cases of small data (which happens when we use CMS as a value with highly skewed keys).

**Comment by reconditesea** [comment]
You mean keep a map of all values to their exact frequencies, until we reach the full size of the counting table? And this should be used when there is a strong prior that the input stream is highly sparsed and skewed?

**Comment by johnynek** [comment]
Yes: keep a `Map[K, Long]` until the number of values is `width * depth` or something, since there is no need to use a CMS until you are already keeping a lot of values.

This can be a subclass of `CMS` similar to `CMSItem`.
