### ISSUE TITLE
Aggregate Option[Numeric] and skip None

### ISSUE THREAD

**Issue by dafox7777777** [twitter/algebird#487]
Hello,

I would like calculate average on Option[Long] items instead of Long/Numeric. I need to skip missing None values in aggregation.
Example:
```scala
case class Move(up: Option[Long],  down: Option[Long])
val aggUp = AveragedValue.aggregator.composePrepare[Move](_.up)
val aggDown = AveragedValue.aggregator.composePrepare[Move](_.down)
val AGG = GeneratedTupleAggregator.from2(aggUp, aggDown)
val moves = TypedPipe.from(List(Move(Some(1), None), Move(None, Some(5)), Move(Some(1), Some(5))))
val average = moves.aggregate(AGG)
```
Is it possible with current Algebird implementation?

I know I can prefilter input, but then can not use GeneratedTupleAggregator or joining of aggregators as obvious from example.

**Comment by avibryant** [comment]
Yes, you can use `sumBefore` to turn a `MonoidAggregator` that takes `A` into one that takes `Traversable[A]` (and `Option[A]` implicitly converts to this).

**Comment by dafox7777777** [comment]
Hello @avibryant not sure how it helps me with Aggregation. I still need to transform None or Traversable[A] to Double in composePrepare method. Could you please provide code example? I tried following:
```
AveragedValue.aggregator.lift.sumBefore.composePrepare[TraversableOnce[Long]](_)
```

**Comment by jnievelt** [comment]
I think you'd do the sumBefore after the composePrepare.

That being said, calculating mean value is a Group (Monoid, etc.), up to a degree of rounding errors.  I'd suggest constructing a Monoid that computes the mean of Option\[Long\] instead of using an aggregator.  If you really do need an aggregator, you can then build the MonoidAggregator from there.

It would be something like:
```
implicit val optMonoid = new OptionMonoid()(AveragedGroup)
val inputs: Seq[(Option[AveragedValue], Option[AveragedValue])] = Seq(
  (Some(AveragedValue(5)), None),
  (Some(AveragedValue(9)), Some(AveragedValue(12)))
)
Monoid.sum(inputs)
```

**Comment by johnynek** [comment]
@dafox7777777 welcome to scala, even contributors of the library don't much agree on what to do.

You might want:
```scala
scala> AveragedValue.numericAggregator[Long].sumBefore.composePrepare[Option[Long]](_.toIterator)
res0: com.twitter.algebird.MonoidAggregator[Option[Long],com.twitter.algebird.AveragedValue,Double] = com.twitter.algebird.MonoidAggregator$$anon$5@5b29a642

scala> res0(List(Some(1), None, Some(2), None))
res1: Double = 1.5
```
If you want to go @jnievelt 's route, I would not set up the monoid, it is the default. Instead I'd do:
```scala
scala> val data: List[Option[Long]] = List(Some(1L), None, Some(2L), None, Some(3L))
scala> Monoid.sum(data.map(_.map(AveragedValue(_))))

res2: Option[com.twitter.algebird.AveragedValue] = Some(AveragedValue(3,2.0))
```

**Comment by dafox7777777** [comment]
Thanks for your answers. I have used @jnievelt 's route with MonoidAggregator.
