### ISSUE TITLE
Seed parameter in `BloomFilter` is unused

### ISSUE THREAD

**Issue by huitseeker** [twitter/algebird#505]
The `seed` parameter of the `BloomFilter` supposedly passed through to Cassandra's 128-bits MurmurHash to initialize the hashing (through https://github.com/twitter/algebird/blob/develop/algebird-core/src/main/scala/com/twitter/algebird/BloomFilter.scala#L80) is in fact not used.

**Comment by ianoc** [comment]
Looks like a long ago PR slipped through the cracks to remove this parameter @ https://github.com/twitter/algebird/pull/220

**Comment by sritchie** [comment]
Fixed by #557
