### ISSUE TITLE
Use macro to replace GenTupleAggregators.scala

### ISSUE THREAD

**Issue by jcoveney** [twitter/algebird#516]
It seems like this file could be replaced by a small macro

https://github.com/twitter/algebird/blob/develop/project/GenTupleAggregators.scala

Not sure if there's any reason not to? Not sure what our stance on macros in algebird is?

**Comment by jnievelt** [comment]
I've not heard of it coming up.  I imagine no one's gotten around to it since we've been on 2.10+

**Comment by johnynek** [comment]
we have macros to generate case class monoid and Arbitrary instances.

that said, macros are hard to debug, slow down compilation, and are not welcoming to newcomers. For tuple stuff that we can codegen once, I would do it.

case classes or other cases is where I would stick the macros.
