### ISSUE TITLE
Maven algebird repository missing

### ISSUE THREAD

**Issue by vincenttsang** [twitter/algebird#522]
Hi, all

I got a problem while I was using Maven to build the HiBench project (which adopts **algebird** in some of its modules), the maven logs are as follows, showing that the site: https://oss.sonatype.org/content/groups/scala-tools/ is unavailable. I then tried to access it through my browser, and discovered that though the oss.sonatype.org website works, the scala-tools directory is missing. 
So could anyone give me some advice to find an **accessible algebird repository for Maven**? 
Thanks a lot!

[ERROR] Failed to execute goal on project streaming-bench-spark_0.1: Could not resolve dependencies for project com.intel.hibench.streambench:streaming-bench-spark_0.1:jar:5.0-SNAPSHOT: Failed to collect dependencies at com.twitter:algebird-core_2.10:jar:0.1.11: Failed to read artifact descriptor for com.twitter:algebird-core_2.10:jar:0.1.11: Could not transfer artifact com.twitter:algebird-core_2.10:pom:0.1.11 from/to scala-tools.org (https://oss.sonatype.org/content/groups/scala-tools/): Access denied to: https://oss.sonatype.org/content/groups/scala-tools/com/twitter/algebird-core_2.10/0.1.11/algebird-core_2.10-0.1.11.pom , ReasonPhrase:Forbidden. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :streaming-bench-spark_0.1

**Comment by bigsnarfdude** [comment]
@vincenttsang http://mvnrepository.com/artifact/com.twitter/algebird-core_2.10

**Comment by johnynek** [comment]
By the way, that is a super old version of algebird. I would encourage them
to upgrade.

On Saturday, June 18, 2016, Vincent Ohprecio <notifications@github.com>
wrote:

> @vincenttsang <https://github.com/vincenttsang>
> http://mvnrepository.com/artifact/com.twitter/algebird-core_2.10
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/twitter/algebird/issues/522#issuecomment-226982571>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAEJdiXqqbejsAfRX9HbHdu2KItSNLgJks5qNOYvgaJpZM4IW3QL>
> .
>


-- 
P. Oscar Boykin, Ph.D. | http://twitter.com/posco | http://pobox.com/~boykin

**Comment by vincenttsang** [comment]
Thank u all guys, my problem was solved through other methods, still, thanks!
