### ISSUE TITLE
BytesSpec is a flakey test

### ISSUE THREAD

**Issue by johnynek** [twitter/algebird#524]
```
[info] BytesSpec:
[info] - requires non-null arrays
[info] - has a sane equals function
[info] - has a sane hashCode function *** FAILED ***
[info]   NoSuchElementException was thrown during property evaluation.
[info]     Message: next on empty iterator
[info]     Occurred when passed generated values (
[info]       wordLength = 0
[info]     )
```

**Comment by johnynek** [comment]
this calls `head` but does not check it if is empty:

https://github.com/twitter/algebird/blob/develop/algebird-test/src/test/scala/com/twitter/algebird/BytesSpec.scala#L81

@jnievelt is that part of the change you added?

**Comment by jnievelt** [comment]
Not sure if you're thinking of my change in scalding.  Looks like this one hasn't changed in over a year.

**Comment by jnievelt** [comment]
Oh maybe you're thinking of #510

**Comment by jnievelt** [comment]
Ah I did break it!  Must have missed that it's `head` outside of any length check.
