### ISSUE TITLE
Many property-based tests are broken

### ISSUE THREAD

**Issue by non** [twitter/algebird#528]
If you change the associativity property to always return `false`, you should see every law check fail. Instead, many of them continue passing, because they are never actually doing any work. This is due to failing to mix-in the correct traits into the test classes.

To fix this, find the tests that pass under a bogus associativity check, change them all so they fail, and then revert the associativity check. The reporter recommends that all the Algebird property-checks extend a single `AlgebirdProperties` trait to ensure that they all have the same mix-ins, to help avoid this issue in the future.

**Comment by isnotinvain** [comment]
Thanks for finding this. @johnynek this has happened before. I think we need to find a way to use our test library that prevents this case of "the tests are quietly not being executed"

**Comment by isnotinvain** [comment]
@non single base trait is a good start, we should definitely standardize everything to that and use only a single scalatest "style"

**Comment by sritchie** [comment]
Looks like we hit this a while ago: https://github.com/twitter/algebird/issues/357

**Comment by sritchie** [comment]
Closed by #584. `TopPCTCmsLaws` and `BatchedLaws` were the remaining broken tests.
