### ISSUE TITLE
Remove invalid Future/Try Group/Ring

### ISSUE THREAD

**Issue by johnynek** [twitter/algebird#548]
the exceptional cases have no inverse, they should be removed (we are clearly using bad test generators or not running tests, we should diagnose that as well).

**Comment by sritchie** [comment]
Closed by #579.

**Comment by sritchie** [comment]
Re-opened - I've marked them as deprecated, but they need to get removed at the next binary incompatible version.

**Comment by johnynek** [comment]
Closed by #523
