### ISSUE TITLE
implement StreamSummary for heavy hitters and frequent elems

### ISSUE THREAD

**Issue by sritchie** [twitter/algebird#561]
Here's the paper: http://www.cse.ust.hk/~raywong/comp5331/References/EfficientComputationOfFrequentAndTop-kElementsInDataStreams.pdf

[From this excellent blog post](https://highlyscalable.wordpress.com/2012/05/01/probabilistic-structures-web-analytics-data-mining/):

> Stream-Summary allows one to detect most frequent items in the dataset and estimate their frequencies with explicitly tracked estimation error... Stream-Summary is able not only to provide estimates, but to answer are these estimates exact (guaranteed) or not.

**Comment by johnynek** [comment]
Isn't that this:
https://github.com/twitter/algebird/blob/develop/algebird-core/src/main/scala/com/twitter/algebird/SpaceSaver.scala

**Comment by sritchie** [comment]
Ah, nice! I even see the note in there now about the explicitly different name :)
