### ISSUE TITLE
Release for Scala 2.12?

### ISSUE THREAD

**Issue by andrewsmartin** [twitter/algebird#574]
I know probably there are some dependencies that have not cross built yet, but is this on the radar?

**Comment by sritchie** [comment]
Definitely something we plan on doing. I don't think anyone has started the process, so we'd definitely be open to a PR that gets this started. Otherwise we should get this started in the next couple of weeks.

**Comment by mosesn** [comment]
new scalatest and scalacheck versions were in service to this, and twitter util should be published for 2.12 soon-ish.

**Comment by andrewsmartin** [comment]
Sure, I'll get this started in a PR.

**Comment by sritchie** [comment]
Thanks @andrewsmartin!

**Comment by sritchie** [comment]
@andrewsmartin, what are you thinking here? We're starting to make noises about Algebird 0.13, and it'd be wonderful if we could publish a build for 2.12!

**Comment by andrewsmartin** [comment]
@sritchie I haven't spent much time on this, sorry! I actually tried quickly around a week ago just by bumping the dependencies to versions that have a 2.12 cross build but if I remember correctly there were some upstream twitter dependencies that hadn't been cross-built yet. I can definitely revisit this today or tomorrow though, but if you'd like to go ahead with this that's fine by me as well!

**Comment by sritchie** [comment]
Hey @andrewsmartin, I can take this one over - Check out #600 for the goodies!

**Comment by andrewsmartin** [comment]
Hey @sritchie, thanks for this! Do you have any idea when we can expect a release to be published?

**Comment by johnynek** [comment]
I want #620 in, then I'm ready.
