### ISSUE TITLE
Widen the visibility of SpaceSaver.SSMany, SpaceSaver.SSOne

### ISSUE THREAD

**Issue by ElPicador** [twitter/algebird#577]
I need to serialize efficiently an instance of `SpaceSaver`. 
For that, I need to access the inner fields `capacity` & `counters`, and the constructors of `SSMany` and `SSOne`.

The issue is both the classes & the constructors are private.

Would it be possible to have them as `public`?

I'm willing to do the PR for this.

**Comment by johnynek** [comment]
Can we instead have a direct serialization method like `HyperLogLog` does?

Exposing inner classes like that makes binary and source compatibility harder.

**Comment by ElPicador** [comment]
It could be an option. 
But the issue I see is that the `counter` in `SpaceSaver` is parametrize with `T`. So how can we encode those objects? Using the default Java serialization is not a good option IMHO.

**Comment by johnynek** [comment]
you can pass something like an injection: `T => Array[Byte], Array[Byte] => Try[T]` and we call as needed.

**Comment by sritchie** [comment]
Thanks for handling this!
