### ISSUE TITLE
binary-incompatible changes for 0.13

### ISSUE THREAD

**Issue by sritchie** [twitter/algebird#587]
These are changes we'd like before we release a binary-incompatible 0.13.

- [x] remove deprecated group/ring for future/try in algebird-util
- [x] convert all `LawsEquiv` versions to take an `Equiv`, and deprecate the `Equiv` version.
- [x] remove count min sketch legacies - `legacy.{ CountMinSketchMonoid, CMS }` (what do you think, @isnotinvain? Are there are uses at Twitter? It's been deprecated since 0.8.1)
- [x] add explicit return types to instances, like `implicit val group` in `AveragedValue.scala`

Small binary-compatible changes:
- [x] Change the generated product algebras to short-circuit if the passed-in iterator is empty
- [x] change the `AveragedValue`.+ test to use `BigInt` vs `Long` so we get full coverage

**Comment by johnynek** [comment]
remove view bounds to doubles and replace with `Numeric[T]` style:

eg. https://github.com/twitter/algebird/pull/589/files#diff-030402b91914cb17675146d882df3148R52

**Comment by johnynek** [comment]
We also want 2.12 support.

**Comment by isnotinvain** [comment]
Update re: legacy.* -- we don't use any at Twitter

**Comment by sritchie** [comment]
nice!

**Comment by sritchie** [comment]
Other than 2.12, these are all closed.
