### ISSUE TITLE
PairMonoid/Semigroup to combine Set/Hyperloglog

### ISSUE THREAD

**Issue by johnynek** [twitter/algebird#59]
Here is the idea, two functions:

``` scala
sealed abstract class EitherAlgebra[+L,+R]
case class LeftAlg[+L](get: L) extends EitherAlgebra[L, Nothing]
case class RightAlg[+R](get: R) extends EitherAlgebra[Nothing,R]

//Then we have a monoid/semigroup on L,R and:

def monoid(shouldConvert: (R) => Boolean, convert: (R) => L): Monoid[EitherAlgebra[L,R]]

```

Then, shouldConvert(s: Set[T]) = s.size > threshold, and convert(s: Set[T]): HLLInstance = iterate over all the items and insert them.

In this way, we can make a monoid that is exact when size is small, and converts to approximate when we cross some size boundary (say about the size of the serialized hyperloglog).

We can do the same with count-min-sketch with a Map[K,Long]. The pattern is: use the exact data structure when the size is less than the approximate, and then switch on demand.

**Comment by sritchie** [comment]
Can we close this now that we have `EventuallyMonoid`?
