### ISSUE TITLE
HLL size estimate for Low cardinality set

### ISSUE THREAD

**Issue by MansurAshraf** [twitter/algebird#628]
I thought with 16 bits estimate would be much closer to the real value for such a small input. Is this the expected behaviour or am I doing something wrong? //cc @johnynek 

```scala
test("HLL") {
    implicit val doubleEquality = TolerantNumerics.tolerantDoubleEquality(0.01)

    val aggregator = HyperLogLogAggregator.sizeAggregator(16)

    val input = List(-233L, 833L)

    val reduced = aggregator.reduce(input.map(x => aggregator.prepare(Injection[Long, Array[Byte]](x))))
    val size = aggregator.present(reduced)
    //size = 1.0000076294721387
    assert(size === 2.0)
  }
```

**Comment by MansurAshraf** [comment]
I think this is because HLL only support positive values but trying to find if its documented somewhere

**Comment by johnynek** [comment]
is there a hash collision by chance?

The sign shouldn't matter since you are mapping it to `Array[Byte]`.

**Comment by MansurAshraf** [comment]
How do I verify hash collision? Basically my property tests are consistently failing for some values.
`List(-8630290981921164368L, -4443196221513724089L)` is another input that fails consistently

**Comment by johnynek** [comment]
```scala
scala> val hll = new HyperLogLogMonoid(16)
hll: com.twitter.algebird.HyperLogLogMonoid = com.twitter.algebird.HyperLogLogMonoid@7f83f52e

scala> hll.toHLL("yo")
res1: com.twitter.algebird.HLL = SparseHLL(16,Map(56608 -> Max(2)))

scala> hll.toHLL("there")
res2: com.twitter.algebird.HLL = SparseHLL(16,Map(28649 -> Max(2)))

scala> hll.sizeOf(hll.plus(res1, res2))
res5: com.twitter.algebird.Approximate[Long] = Approximate(1,2,3,0.9972)

scala> hll.sizeOf(hll.plus(res1, res2)).estimate
res6: Long = 2
```

**Comment by MansurAshraf** [comment]
right its not failing for all values, but some values generated by scalacheck

**Comment by johnynek** [comment]
hash collision:
```scala
scala> hll.toHLL(-233L)
res17: com.twitter.algebird.HLL = SparseHLL(16,Map(534 -> Max(1)))

scala> hll.toHLL(833L)
res18: com.twitter.algebird.HLL = SparseHLL(16,Map(534 -> Max(1)))

scala> hll.plus(res17, res18)
res19: com.twitter.algebird.HLL = SparseHLL(16,Map(534 -> Max(1)))
```

**Comment by johnynek** [comment]
surprising to find it.

**Comment by johnynek** [comment]
Work around is to customize the hash function perhaps if you have not serialized hashes already.

Here is one that xors the long into the hash function after, which might reduce collisions for Longs.

```scala
scala> implicit val hashLong: Hash128[Long] = new Hash128[Long] { def DefaultSeed = Hash128.longHash.DefaultSeed; def hashWithSeed(seed: Long, k: Long) = { val (a, b) = Hash128.longHash.hashWithSeed(seed, k); (a ^ k, b ^ k) } }
hashLong: com.twitter.algebird.Hash128[Long] = $anon$1@1f92597a

scala> hll.toHLL(-233L)
res20: com.twitter.algebird.HLL = SparseHLL(16,Map(65001 -> Max(9)))

scala> hll.toHLL(833L)
res21: com.twitter.algebird.HLL = SparseHLL(16,Map(534 -> Max(1)))

scala> hll.plus(res20, res21)
res22: com.twitter.algebird.HLL = SparseHLL(16,Map(534 -> Max(1), 65001 -> Max(9)))

scala> hll.sizeOf(hll.plus(res20, res21))
res23: com.twitter.algebird.Approximate[Long] = Approximate(1,2,3,0.9972)
```

**Comment by MansurAshraf** [comment]
can we make this new hash function as default or thats not possible?

**Comment by johnynek** [comment]
That would break anyone that has serialized old HLLs. And also we don't know that has fewer collisions anyway (it may still have just as many).

You could do some testing and try to find a `Hash128` that has no collisions on Longs (it is possible, 64 bits to 128 bits clearly does not have to collide), but you also want some nice properties of the bits (i.e. they are as likely to be 0 as 1).

Once you do that, you can add this to an `import` where you need it, or make a new-type wrapper:

`case class CollisionFreeLong(toLong: Long) extends AnyVal`

**Comment by johnynek** [comment]
closing this since we got to the bottom of it, and we don't want to change the hash functions for fear of wrecking serialized data.

Users affected are encouraged to implement their own Hash128.
