### ISSUE TITLE
Size on saturated bloom filter throws an exception

### ISSUE THREAD

**Issue by cacts** [twitter/algebird#632]
using the following example:

```
import com.twitter.algebird._
import scala.util.Random

implicit val hash = Hash128.stringHash
val bf = BloomFilter(2, 0.05)
val strings = for (_ <- 0 to 9) yield Random.nextString(5)

val filter = bf.create(strings: _*)
println(filter.size.estimate)
```

we get:

> java.lang.IllegalArgumentException: requirement failed
> 	at scala.Predef$.require(test.sc:208)
> 	at com.twitter.algebird.Approximate.<init>(test.sc:73)
> 	at com.twitter.algebird.BloomFilter$.sizeEstimate(test.sc:168)
> 	at com.twitter.algebird.BFInstance.size(test.sc:595)

in previous versions (0.11.0) the Approximate returned by size would be invalid, but now throws an exception due to the assertion.

**Comment by cesarcolle** [comment]
I reproduce : 
for an input like : 
```scala
Array(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
```
From the BloomFilter object, the size method use 
```scala
def sizeEstimate(numBits: Int,
                   numHashes: Int,
                   width: Int,
                   approximationWidth: Double = 0.05): Approximate[Long] = ???
```
return an _Approximate_ object like : 

```scala
Approximate(min = 0, estimate = -1, max = 0, prob =  1.0)
```

This fail with the : 
```scala
require(numeric.lteq(min, estimate) && numeric.lteq(estimate, max))
```
 property of the Approximate object.
This issue can be handle from the BloomFilter or the Approximate object.

I can fix it but I don't know where to start :)

**Comment by johnynek** [comment]
Great...

Step 1: send a PR with the failing test.
Step 2: lets investigate why the invariant is false, having an estimate of -1 when the min is 0 is a problem. We probably have some arithmetic issue here, or some other problem.
Step 3: fix the bug and watch PR go green.

Happy to review the code!
