### ISSUE TITLE
`Successible` should be `Serializable`

### ISSUE THREAD

**Issue by ttim** [twitter/algebird#635]
Most of our type classes are `Serializable`, including `Predecessible`. Same should apply to `Successible`.

**Comment by johnynek** [comment]
closed by: https://github.com/twitter/algebird/commit/3b78165ca3f0a6cb6ba3de6467f4fe1fce5c4b75

which I accidentally pushed to develop. It is so trivial, I don't want to bother with the revert unless someone is really concerned.
