### ISSUE TITLE
Using the inliner (-opt:l:classpath) causes binary incompatible releases

### ISSUE THREAD

**Issue by lrytz** [twitter/algebird#640]
Algebird 0.13.0 for Scala 2.12 (built with Scala 2.12.1) is not binary compatible with Scala 2.12.3, which causes a `NoSuchMethodError` at run-time. This is because inlining from the classpath is enabled in the build (https://github.com/twitter/algebird/blob/0.13.0/build.sbt#L80-L85).

From the [2.12.0 release notes](http://www.scala-lang.org/news/2.12.0/):

> When inlining code from the classpath, you must ensure that all dependencies have exactly the same versions at compile time and run time.
> If you are building a library to publish on Maven Central, you should not inline code from dependencies. Users of your library might have different versions of those dependencies on the classpath, which breaks binary compatibility.

Note that 2.12.3 deprecates `-opt:l:classpath`, introduces `-opt:l:inline`, and a new setting `-opt-inline-from` which tells the inliner where from which packages it is allowed to inline from. See https://github.com/scala/scala/pull/5964.

**Comment by lrytz** [comment]
Details on the binary incompatibility here: https://github.com/scala/bug/issues/10489#issuecomment-327097429

**Comment by johnynek** [comment]
we have an open PR on this now:

https://github.com/twitter/algebird/pull/639
