### ISSUE TITLE
New point release that includes BigDecimal semigroup

### ISSUE THREAD

**Issue by snoble** [twitter/algebird#642]
In particular it would be valuable to have a point release that includes https://github.com/twitter/algebird/commit/757712c3eb872b478153c8c1de934d00dcf87f28

Many thanks!

**Comment by johnynek** [comment]
@piyushnarang would you have any time for this when (if) you do bijection?

**Comment by johnynek** [comment]
@piyushnarang I think we are almost ready if we can merge #643 

It would help us to be able to publish. Do you have time or can you give me the 👍  to publish?

**Comment by johnynek** [comment]
I think develop is in shape to be the new point release.

**Comment by piyushnarang** [comment]
@johnynek I'm in favor of a release, I'm guessing it's going to be 0.13.1? I'm probably not going to have time to get to it, but if you've got the sonatype perms etc feel free to do so. 
@pankajroark wdyt?

**Comment by oscar-stripe** [comment]
I think actually it can be 0.12.x since mima should be running.
I'll re-run.

**Comment by pankajroark** [comment]
👍

**Comment by oscar-stripe** [comment]
oh yeah, that is 0.13.1... sorry, you are right @piyushnarang

**Comment by oscar-stripe** [comment]
just re-ran mima. Looks clean with `0.13.0`. Will republish.

**Comment by piyushnarang** [comment]
Ok great, thanks!

**Comment by johnynek** [comment]
https://github.com/twitter/algebird/releases/tag/v0.13.1
