### ISSUE TITLE
Scala 2.13.x

### ISSUE THREAD

**Issue by regadas** [twitter/algebird#671]
Hello!

I was wondering if there's anything planned to cross compile to 2.13.
Probably some of the modules will not be possible for quite some time, like `algebird-spark`.

**Comment by johnynek** [comment]
Happy to take PRs!

**Comment by skonto** [comment]
I am wondering about the `algebird-spark` dependency. Spark requires chill and chill requires `algebird-core`. Can we have independent releases per module per scala version?

**Comment by johnynek** [comment]
We can, but it is a pain with SBT. But doable. We have done it in the past before spark has 2.12 support.

**Comment by ayoub-benali** [comment]
Is this issue worked on ?

**Comment by johnynek** [comment]
I don’t know if anyone is working on it now. The other ticket referenced above had some blockers.

**Comment by regadas** [comment]
Hi, just wanted to let you know that I got around to compile `algebird-core` with `2.13` I should be able to PR something soonish ™️

**Comment by johnynek** [comment]
Amazing! That’s really great.

**Comment by regadas** [comment]
@johnynek is it still important to keep support for 2.10?

The reason I'm asking is because some deps needed for 2.13 stopped being published for 2.10. This leads us to situation where we might have cross compilation with different dep versions. I don't think this is ideal and should be avoided.

**Comment by SethTisue** [comment]
continued support for 2.10 is becoming increasingly rare in Scala OSS. dropping it sounds reasonable to me

**Comment by johnynek** [comment]
Yeah, dropping 2.10 is fine.

**Comment by h-vetinari** [comment]
Xref #719, which added 2.13 support for all but
- [ ] algebird-bijection (blocked on twitter/bijection#287)
- [ ] algebird-spark

Also, 2.10 was dropped in #721.

**Comment by regadas** [comment]
`algebird-bijection` support is added in https://github.com/twitter/algebird/pull/776

TBH I don't know the status of `spark` supporting 2.13. I guess it will take awhile.

Should we close this issue?

**Comment by johnynek** [comment]
Thanks, I guess spark support will have to wait until spark 3?
