### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by regadas** [twitter/algebird#969]
Hi @johnynek!

I was thinking that we could cut a new release; we haven't done one in awhile.

for this one we have:
* scala 2.13.5
* a bunch of dep updates
* the immutable bloom filter
* fixes

wdyt?

**Comment by johnynek** [comment]
Sounds good to me.

I think we have the automatic tag based publish here. IIRC.

**Comment by regadas** [comment]
Cool! I'll take a look at it later then.

**Comment by regadas** [comment]
https://github.com/twitter/algebird/releases/tag/v0.13.8 is out. Thank you!

**Comment by johnynek** [comment]
Thanks, this is great!

I guess we need a scala 3 build eventually...
